--- 
- name: Install Packages for Wordpress (Ubuntu)
  ansible.builtin.apt: 
    wordpress_required_packages_ubuntu:
    update_cache: yes 

- name: Enable service httpd and ensure it is not masked
  ansible.builtin.systemd: 
    name: apache2 
    enabled: true 
    masked: no
    state: started 

- name: Change file ownership, group and permissions
  ansible.builtin.file: 
    path: /var/www/html
    owner: "{{ ansible_user }}"
    group: www-data
    mode: '0664'
    recurse: true

- name: Unarchive wordpress 
  ansible.builtin.unarchive: 
    src: https://wordpress.org/latest.tar.gz
    dest: /var/www/html 
    remote_src: yes 
    owner: "{{ ansible_user }}"
    group: www-data 
    extra_opts: [--strip-components=1]

- name: Update config 
  template: 
    src: wp-config.php.j2
    dest: /var/www/html/wp-config.php 

- name: Change file ownership, group and permissions
  ansible.builtin.file: 
    path: /var/www/html
    owner: "{{ ansible_user }}"
    group: www-data
    mode: u=rwX,g=rwX,o=rX 
    recurse: true
    state: directory

- name: Remove old index file
  ansible.builtin.file: 
    path: /var/www/html/index.html 
    state: absent

- name: Enable .htaccess files in Apache config
  ansible.builtin.replace:
    path:  /etc/apache2/apache2.conf
    after: '<Directory /var/www/>'
    before: '</Directory>'
    regexp: 'AllowOverride None'
    replace: |
      AllowOverride All
      RequestHeader set X-Forwarded-Proto "https"
      RequestHeader set X-Forwarded-Port "443"
  notify:
    - restart apache2

- name: Create a symbolic link for mod_headers
  ansible.builtin.file:
    src: /etc/apache2/mods-available/headers.load
    dest: /etc/apache2/mods-enabled/headers.load
    state: link
  notify:
    - restart apache2

...